archives:
    ait:
        name: 'Archive-It'
        info: 'https://archive-it.org/'

        type: memento
        timegate_url: http://wayback.archive-it.org/all/{url}
        timemap_url: http://wayback.archive-it.org/all/timemap/link/{url}
        replay_url: http://wayback.archive-it.org/all/{timestamp}id_/{url}

    ait_coll:
        name: 'Archive-It Collections'
        info: 'https://archive-it.org/'

        type: cdx
        api_url: 'https://wayback.archive-it.org/cdx?url={url}&filter=filename:ARCHIVEIT-({src_coll})-.*'
        replay_url: https://wayback.archive-it.org/{src_coll}/{timestamp}id_/{url}
        parse_collection: true

    ba:
        name: 'Bibliotheca Alexandrina Web Archive'
        info: 'http://www.bibalex.org/isis/frontend/archive/archive_web.aspx'

        type: memento
        timegate_url: http://web.archive.bibalex.org/web/{url}
        timemap_url: http://web.archive.bibalex.org/web/timemap/link/{url}
        replay_url: http://web.archive.bibalex.org/web/{timestamp}im_/{url}

    bl:
        name: 'UK Web Archive'
        info: 'http://www.webarchive.org.uk/ukwa/'

        type: memento
        timegate_url: https://www.webarchive.org.uk/wayback/archive/{url}
        timemap_url: https://www.webarchive.org.uk/wayback/archive/timemap/link/{url}
        replay_url: https://www.webarchive.org.uk/wayback/archive/{timestamp}id_/{url}

    ia:
        name: 'Internet Archive'
        info: 'https://archive.org/web/'

        type: memento
        timegate_url: https://web.archive.org/web/{url}
        timemap_url: https://web.archive.org/web/timemap/link/{url}
        replay_url: https://web.archive.org/web/{timestamp}id_/{url}

    is:
        name: 'Icelandic Web Archive'
        info: 'http://vefsafn.is/'

        type: memento
        timegate_url: http://wayback.vefsafn.is/wayback/{url}
        timemap_url: http://wayback.vefsafn.is/wayback/timemap/link/{url}
        replay_url: http://wayback.vefsafn.is/wayback/{timestamp}id_/{url}

    loc:
        name: 'Library of Congress'
        info: 'http://loc.gov/websites/'

        type: memento
        timegate_url: http://webarchive.loc.gov/all/{url}
        timemap_url: http://webarchive.loc.gov/all/timemap/link/{url}
        replay_url: http://webarchive.loc.gov/all/{timestamp}id_/{url}

    pwa:
        name: 'Portuguese Web Archive'
        info: 'http://arquivo.pt/'

        type: memento
        timegate_url: http://arquivo.pt/wayback/{url}
        timemap_url: http://arquivo.pt/wayback/timemap/*/{url}
        replay_url: http://arquivo.pt/wayback/{timestamp}id_/{url}

    rhiz:
        name: 'Rhizome Webenact'
        info: 'http://webenact.rhizome.org/'

        type: memento
        timegate_url: http://webenact.rhizome.org/all/{url}
        timemap_url: http://webenact.rhizome.org/all/timemap/*/{url}
        replay_url: http://webenact.rhizome.org/all/{timestamp}id_/{url}

    swa:
        name: 'Stanford Web Archive'
        info: 'https://swap.stanford.edu/'

        type: memento
        timegate_url: https://swap.stanford.edu/{url}
        timemap_url: https://swap.stanford.edu/timemap/link/{url}
        replay_url: https://swap.stanford.edu/{timestamp}id_/{url}


